stages:
  - build
  - make
  - deploy
  
variables:
  VERSION: "1.$CI_PIPELINE_ID"
  BUILDDIR: "/builds"
  LOCALDIR: "/opt/gitlab-runner/builds"

#rtc-sonar:
#  tags:
#    - test-rtc-shell
#  stage: build
#  only:
#    - test
#  script:
#    - /opt/sonar_analyze.sh
  
mixer-build:
  tags:
    - lvs12-mixer-docker
  stage: build
  only:
    - develop
  retry: 2
  script:
    - pwd
    - mkdir -p ${BUILDDIR}/ffmpeg/target/ bin/plugins
    - rm -rf ${BUILDDIR}/ffmpeg/target/*
    - ulimit -c unlimited
    - make
    - mv bin/plugins/libffmpeg.so lib ${BUILDDIR}/target/
    - cd bin
    - ./mixerTestd ./template.json ./task.json
