stages:
  - build
  - make
  - deploy
  
variables:
  VERSION: "1.$CI_PIPELINE_ID"
  BUILDDIR: "/builds"
  LOCALDIR: "/opt/gitlab-runner/builds"

#rtc-sonar:
#  tags:
#    - test-rtc-shell
#  stage: build
#  only:
#    - test
#  script:
#    - /opt/sonar_analyze.sh
  
mixer-build:
  tags:
    - lvs12-mixer-docker
  stage: build
  only:
    - develop
  retry: 1
  script:
    - pwd
    - ffmpeg=${BUILDDIR}/ffmpeg
    - mkdir -p ${ffmpeg}/target/plugins bin/plugins
    - rm -rf ${ffmpeg}/target/*
    - ulimit -c unlimited
    - make
    - cp -f bin/plugins/libffmpeg.so ${ffmpeg}/target/plugins/
    - cp -a inc lib bin ${ffmpeg}/target/
    - cp -f lib/* /usr/local/lib/
    - ldconfig
    - cd bin
    - ./mixerTest ./template.json ./task.json
    - ls -R ${ffmpeg}/target/