stages:
  - build
  - make
  - deploy
  
variables:
  VERSION: "1.$CI_PIPELINE_ID"
  BUILDDIR: "/builds"
  LOCALDIR: "/opt/gitlab-runner/builds"

#rtc-sonar:
#  tags:
#    - test-rtc-shell
#  stage: build
#  only:
#    - test
#  script:
#    - /opt/sonar_analyze.sh
  
mixer-build:
  tags:
    - lvs12-mixer-docker
  stage: build
  only:
    - develop
  retry: 1
  script:
    - workdir=$(pwd)
    - if [ -d "${ffmpeg}/target" ];then mkdir -p ${ffmpeg}/target;fi
    - rm -rf ${ffmpeg}/target/*
    - ffmpeg=${BUILDDIR}/ffmpeg
    - mkdir -p ${ffmpeg}/target/plugins bin/plugins
    - ulimit -c unlimited
    - make
    - echo -e "\e[40;32m 编译 libavformat.so.57 \e[0m"
    - cd ./third-party/ffSDK/src
    - configure --enable-shared
    - make
    - cd ${workdir}
    - cp -f ./third-party/ffSDK/lib/libavformat.so.57 lib/
    - cp -f bin/plugins/libffmpeg.so ${ffmpeg}/target/plugins/
    - cp -a inc lib bin ${ffmpeg}/target/
    - cp -f lib/* /usr/local/lib/
    - ldconfig
    - cd bin
    - /lib/x86_64-linux-gnu/libc.so.6
    - ./mixerTest ./template.json ./task.json
    - ls -R ${ffmpeg}/target/