stages:
  - build
  - make
  - deploy
  
variables:
  VERSION: "1.$CI_PIPELINE_ID"
  BUILDDIR: "/builds"
  LOCALDIR: "/opt/gitlab-runner/builds"

#rtc-sonar:
#  tags:
#    - test-rtc-shell
#  stage: build
#  only:
#    - test
#  script:
#    - /opt/sonar_analyze.sh
  
mixer-build:
  tags:
    - lvs12-mixer-docker
  stage: build
  only:
    - develop
  before_script:
    - changeFiles=$(git diff --name-only HEAD~ HEAD)
    - isSDKChanged=0
    - for i in ${changeFiles[@]};do
    - if [[ $i == *third-party/ffSDK* ]];then echo $i;isSDKChanged=1&&break;fi
    - done
    - if [ $isSDKChanged -gt 0 ];then
    - sed -i "s|deb.debian.org|mirrors.aliyun.com|g" /etc/apt/sources.list
    - sed -i 's|security.debian.org|mirrors.aliyun.com|g' /etc/apt/sources.list
    - apt update
    - apt install -y --no-install-recommends yasm
    - echo -e "\e[40;31m 编译 libavformat.so.57 \e[0m" 
    - cd ./third-party/ffSDK/src 
    - ./configure --enable-shared
    - make
    - fi
  script:
    - workdir=$(pwd)
    # - sed -i "s|deb.debian.org|mirrors.aliyun.com|g" /etc/apt/sources.list
    # - sed -i 's|security.debian.org|mirrors.aliyun.com|g' /etc/apt/sources.list
    # - apt update
    # - apt install -y --no-install-recommends yasm
    # - echo -e "\e[40;31m 编译 libavformat.so.57 \e[0m"
    # - cd ./third-party/ffSDK/src
    # - ./configure --enable-shared
    # - make
    - if [ -d "${ffmpeg}/target" ];then mkdir -p ${ffmpeg}/target;fi
    - rm -rf ${ffmpeg}/target/*
    - ffmpeg=${BUILDDIR}/ffmpeg
    - mkdir -p ${ffmpeg}/target/plugins bin/plugins
    - ulimit -c unlimited
    - cd ${workdir}
    # - find ${workdir} -name "libavformat*"
    - make
    - mkdir -p lib
    - cp -f ./third-party/ffSDK/src/libavformat/libavformat.so.57 lib/
    - cp -f bin/plugins/libffmpeg.so ${ffmpeg}/target/plugins/
    - cp -a inc lib bin ${ffmpeg}/target/
    - cp -f lib/* /usr/local/lib/
    - ldconfig
    - cd bin
    - /lib/x86_64-linux-gnu/libc.so.6
    - ./mixerTest ./template.json ./task.json
    - ls -R ${ffmpeg}/target/